apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-regel-api-arena-adapter
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8093
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{ replicas.min }}
    max: {{ replicas.max }}
  resources:
    limits:
      memory: {{ resources.limits.memory }}
    requests:
      cpu: {{ resources.requests.cpu }}
      memory: {{ resources.requests.memory }}
  ingresses:
    - {{ ingress }}
  secureLogs:
    enabled: true
  vault:
    enabled: true
  azure:
    application:
      enabled: true
  # required for on-premises only
  webproxy: true

