#!/usr/bin/env bash

echo $PWD


CUCUMBER_ENV=dev


echo 'Running uat tests'

echo 'Env vars *******************************************'

env

echo 'Env vars stop *******************************************'



./gradlew uat --debug