#!/usr/bin/env bash

echo $PWD

echo 'Running uat tests'

echo 'Gradle properties  *******************************************'

 ./gradlew properties


echo 'Gradle properties stop *******************************************'


./gradlew uat